### ISSUE TITLE
TODOzão GERAL

### ISSUE THREAD

**Issue by danielkeizoy** [glaydsonp/TrabalhoNP2TerceiroSemestre#5]
**//TODO**
    
**main >** 
	

- [x] lê todos os CSV
- [x] 	executa menu
- [ ] 	sobrescreve os CSV

**> fim**

	**Menu**

- [ ] listarHistorico()
- [ ] listarRelatorio()
- [ ] incluirRendimento()

	**Model**

- [x] listarCurso()
- [x] listarAluno()
- [ ] listarHistorico()
- [ ] listarRelatorio()
- [ ] incluirRendimento()
- [ ] conferir compareTo() do Curso

	**Control**

- [x] CorpoDeAlunos
- [x] GradeDeCursos

- [x] controle de erros try-catch

**Comment by glaydsonp** [comment]
Nice! 

Feito hoje: 
• Lógica para ler os arquivos: cursos.csv e aluno.csv. 
• Lógica para listar todos os alunos e todos os cursos.

Reta final, guys!
